services:
  - type: web
    name: Goggle-Ai-Agent---Blog-Agent
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p data/sessions
    startCommand: |
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    allowedPaths:
      - data/sessions
